### ISSUE TITLE
Published release never showed up after successful webhook

### ISSUE THREAD

**Issue by KyleJune** [denoland/dotland#2696]
On Feb 19th @ 5:41:38 PM CST, I pushed the tag 0.5.0 to github for my udibo_react_app module.

https://github.com/udibo/react_app/releases/tag/0.5.0

The webhook had the following response showing it was successful.

```json
{"success":true,"data":{"module":"udibo_react_app","version":"0.5.0","repository":"udibo/react_app","status_url":"https://deno.land/status/522c5bef-8f26-497d-9b77-bded5e333a44"}}
```

If you go to that status url, it shows that it was successful.

https://deno.land/status/522c5bef-8f26-497d-9b77-bded5e333a44

I did try redelivering it but that failed and had this response indicating deno recognizes the version was already pushed.

```json
{"success":false,"error":"version already exists"}
```

The 0.5.0 release still doesn't show up on deno.land/x 6 days later. It shows the latest version is the previous one which is 0.4.0. I've tried clearing my cache and others reported that it doesn't show up for them either.

![image](https://user-images.githubusercontent.com/3241653/221374010-437594b3-9660-41b7-9b15-5953b681d384.png)

https://deno.land/x/udibo_react_app@0.5.0

![image](https://user-images.githubusercontent.com/3241653/221373958-810578a9-980a-4905-8c1c-fd7c493f6ae7.png)

It doesn't show up in the apiland API response either.

https://apiland.deno.dev/v2/metrics/modules/udibo_react_app

```json
{"metrics":{"maintenance":{},"updated":"2023-02-25T00:25:16.889Z","quality":{},"name":"udibo_react_app","popularity":{"score":58,"sessions_30_day":49,"users_30_day":72}},"info":{"defaultModule":{"docable":true,"path":"/mod.tsx","type":"file","size":5358},"kind":"modinfo","module":"udibo_react_app","versions":["0.4.0","0.3.3","0.3.2","0.3.1","0.3.0","0.2.1","0.2.0","0.1.3","0.1.2","0.1.1","0.1.0"],"upload_options":{"ref":"0.4.0","type":"github","repository":"udibo/react_app"},"dependencies":[{"pkg":"http_error","src":"deno.land/x","ver":"0.4.0"},{"ver":"18.2.0","org":"","pkg":"react-dom","src":"esm.sh"},{"org":"","src":"esm.sh","ver":"3.1.4","pkg":"react-error-boundary"},{"pkg":"react-helmet-async","ver":"1.3.0","org":"","src":"esm.sh"},{"ver":"6.6.1","pkg":"react-router-dom","org":"","src":"esm.sh"},{"ver":"18.2.0","org":"","pkg":"react","src":"esm.sh"}],"uploaded_at":"2023-02-19T03:29:15.260Z","tags":[],"description":"A React Framework for Deno that makes it easy to create highly interactive apps that have server side rendering with file based routing for both your UI and API.","dependency_errors":[],"config":{"type":"file","size":763,"path":"/deno.jsonc"},"readme":{"path":"/README.md","type":"file","size":11246},"version":"0.4.0","latest_version":"0.4.0"}}
```

When I brought this up in #dev-website on discord. @crowlKats agreed this was strange and also found that it does show version 0.5.0 at this API endpoint.

https://cdn.deno.land/udibo_react_app/meta/versions.json

```json
{"latest":"0.5.0","versions":["0.5.0","0.4.0","0.3.3","0.3.2","0.3.1","0.3.0","0.2.1","0.2.0","0.1.3","0.1.2","0.1.1","0.1.0"]}
```

Someone else on discord mentioned having this issue and that the missing version showed up for them after they pushed a new release.

https://discord.com/channels/684898665143206084/684898665151594506/1077366647117066300

I have a new release I want to publish today, so the 0.5.0 release might show up afterwards. Hopefully the information in this will be helpful still for investigating the issue even if 0.5.0 starts showing up after I publish 0.5.1. I'll add a comment to this issue about whether or not it shows up afterward.

**Comment by KyleJune** [comment]
I just pushed version 0.5.1. After doing so, version 0.5.0 is showing up.

**Comment by KyleJune** [comment]
I believe this one is different because it was not available even if you changed the URL to use the missing version. In your case it didn't show up in the list but you said you could still go to it by changing the URL to use the missing version.

If I'm wrong and they are the same, this issue has more details, so I think it would be good to keep this issue open.

**Comment by KnorpelSenf** [comment]
I absolutely agree it should stay open since this is still an issue. I was asking out of curiosity :)

Yes, you are right that this issue is different. I was able to access the latest version.
